# MNE-CPP Travis CI for Linux and OS-X
language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: BUILD=linux_release
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: BUILD=osx_release
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: BUILD=linux_tests

before_install: . tools/travis/$BUILD/before_install.sh
install: . tools/travis/$BUILD/install.sh
before_script: . tools/travis/$BUILD/before_script.sh
script: . tools/travis/$BUILD/script.sh
after_success: . tools/travis/$BUILD/after_success.sh

notifications:
  email:
    - christoph.dinh@mne-cpp.org
    - lorenz.esch@mne-cpp.org