language: cpp

compiler: 
    - gcc 

before_install:
    - sudo add-apt-repository -y ppa:beineri/opt-qt56-trusty
    - sudo apt-get -qy update 

install:
    - sudo apt-get -qy install qt56base qt563d
    - source /opt/qt56/bin/qt56-env.sh

before_script:
    - qmake -v
	
script:
   - qmake -r
   - make

after_success:
    - echo "MNE-CPP build successful!";