language: cpp

compiler:
    - clang
    - gcc

sudo: required
dist: trusty

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt56-trusty -y
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq qt56base qt563d qt56svg qt56serialport
    - source /opt/qt56/bin/qt56-env.sh

script:
    - qmake -r
    - make -j2

after_success:
    - echo "MNE-CPP build was successful!";

notifications:
  email:
    - christoph.dinh@mne-cpp.org
    - lorenz.esch@mne-cpp.org