# MNE-CPP Travis CI for Linux and OS-X
language: cpp

os:
    - linux
#    - osx
	
matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
#    - os: osx
#      osx_image: xcode7.3

before_install: . tools/travis/$TRAVIS_OS_NAME/before_install.sh

install: . tools/travis/$TRAVIS_OS_NAME/install.sh

script: . tools/travis/$TRAVIS_OS_NAME/script.sh

after_success: . tools/travis/$TRAVIS_OS_NAME/after_success.sh

notifications:
  email:
    - christoph.dinh@mne-cpp.org
    - lorenz.esch@mne-cpp.org