language: cpp

compiler: 
    - gcc 

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt56-trusty -y
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq qt56base qt563d; source /opt/qt56/bin/qt56-env.sh

script:
   - qmake -r
   - make

after_success:
    - echo "MNE-CPP build successful!";