# MNE-CPP Travis CI for Linux and OS-X
language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: osx
      osx_image: xcode7.3
      compiler: clang

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt56-trusty -y; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq                               ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi

install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq qt56base qt563d qt56svg qt56serialport cppcheck lcov; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /opt/qt56/bin/qt56-env.sh                                             ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip install codecov; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5     ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force qt5; fi

## Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/ 
#before_script: 
#    - "export DISPLAY=:99.0" 
#    - "sh -e /etc/init.d/xvfb start" 
#    - sleep 3 # give xvfb some time to start 

script:
    # QA: static code analysis with CppCheck
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cppcheck --enable=all -f -q -i./include/3rdParty/eigen3 -i/opt/qt56/include ./MNE ./applications ./testframes ./examples; fi
    # Build
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then qmake -r MNECPP_CONFIG+=withCodeCov; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then qmake -r MNECPP_CONFIG+=noTests; fi
    - make -j2

after_success:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./bin/test_codecov; fi
    #tbd: later on do a grep of all cpps within testframe
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gcov ./testframes/test_codecov/test_codecov.cpp; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ls; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ls ./bin/; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then codecov; fi
#    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email:
    - christoph.dinh@mne-cpp.org
    - lorenz.esch@mne-cpp.org