# MNE-CPP AppVeyor CI for Windows

# version format 
version: 1.0.0-{build} 

#os: Visual Studio 2015 #takes currently too long (> 1h)
platform: x64 

install:
#    - set QTDIR=C:\Qt\5.6\msvc2015_64
    - set QTDIR=C:\Qt\5.6\msvc2013_64
    - set PATH=%PATH%;%QTDIR%\bin
build_script:
#    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
    - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64
    - qmake -r
    - nmake

notifications: 
  - provider: Email 
    to: 
      - christoph.dinh@mne-cpp.org
      - lorenz.esch@mne-cpp.org
    on_build_status_changed: true 
