# MNE-CPP AppVeyor CI for Windows

# version format 
version: 1.0.{build} 

os: Visual Studio 2015
platform: x64 

install:
    - set QTDIR=C:\Qt\5.6\msvc2015_64
    - set PATH=%PATH%;%QTDIR%\bin
build_script:
    - qmake -r
    - nmake

notifications: 
  - provider: Email 
    to: 
      - christoph.dinh@mne-cpp.org
      - lorenz.esch@mne-cpp.org
    on_build_status_changed: true 
