# MNE-CPP AppVeyor CI for Windows

version: 1.0.0-{build} 
pull_requests:
  do_not_increment_build_number: true

os: Visual Studio 2015
platform: x64
configuration: Release

install:
    - set QTDIR=C:\Qt\5.6\msvc2015_64
    - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\Tools\QtCreator\bin;C:\Qt\QtIFW2.0.1\bin
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

build:
  parallel: true
  #quiet|minimal|normal|detailed
  verbosity: detailed 

before_build:
    - cd ..
    - if not exist "mne-cpp_shadow_build" mkdir mne-cpp_shadow_build
    - cd mne-cpp_shadow_build
    #- qmake ../mne-cpp/mne-cpp.pro -r MNECPP_CONFIG+=noTests

build_script:
    #- jom
    - cd ..

#after_build:
    - call .\mne-cpp\tools\appveyor\compress_binaries.bat master
    - call .\mne-cpp\tools\appveyor\build_installer.bat master
    - dir

deploy:
  - provider: FTP
    protocol: ftp
    host:
      secure: ckK4+pPybTYYRiKxXpZScwZlxRmpxUgTvZaTN+vVAfU=
    username:
      secure: aUqYXjXjd4dh3sO18+x8qw==
    password:
      secure: u8DCGb7s6kuPyjybX/THWFQ0VMCfpLD5IsB/9nzGnvk=
    artifact: mne-cpp-windows-x86_64-master.exe mne-cpp-windows-x86_64-master.zip
    on:
      branch: master

notifications: 
  - provider: Email 
    to: 
      - christoph.dinh@mne-cpp.org
      - lorenz.esch@mne-cpp.org
    on_build_status_changed: true